version: '3'

services:

    dev-phpfpm:
        user: "1000:0"
        image: registry.cn-shenzhen.aliyuncs.com/nekoimi/phpfpm7.0:1.0
        expose:
          - "9000"
        networks:
          - dev-network
        volumes:
          - "./:/www"
        restart: always
        privileged: true

networks:
    dev-network:
        driver: bridge
